spring:
  application:
    name: registry_center

server:
  port: 1111


eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    serviceUrl:
      zone1: http://localhost:1111/eureka/
    region: skyler-test
    availability-zones:
      skyler-test: zone1,zone2

  instance:
    metadata-map.zone: zone1




logging:
  level:
    root: info

#    com.netflix.discover: debug
    com.netflix.eureka.registry.ResponseCacheImpl: info
    com.netflix.discovery.shared.NamedConnectionPool: info
    com.netflix: debug
    com.sun.jersey: debug
    org.springframework.cloud.netflix: debug
    org.apache.catalina.authenticator: debug

