spring:
  application:
    name: registry_center

server:
  port: 20280


eureka:
  client:
    # 设置是否将自己作为客户端注册到注册中心（缺省true）
    # 这里为不需要（查看@EnableEurekaServer注解的源码，会发现它间接用到了@EnableDiscoveryClient）
    register-with-eureka: false
    # 设置是否从注册中心获取注册信息（缺省true）
    # 因为这是一个单点的EurekaServer，不需要同步其它EurekaServer节点的数据，故设为false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
#      zone1: http://localhost:1111/eureka/
#    region: skyler-test
#    availability-zones:
#      skyler-test: zone1,zone2
#
#  instance:
#    metadata-map.zone: zone1




logging:
  level:
    root: info

#    com.netflix.discover: debug
    com.netflix.eureka.registry.ResponseCacheImpl: info
    com.netflix.discovery.shared.NamedConnectionPool: info
    com.netflix: debug
    com.sun.jersey: debug
    org.springframework.cloud.netflix: debug
    org.apache.catalina.authenticator: debug

