spring:
  application:
    name: service1
#  zipkin:
#    base-url: http://localhost:3337
#  sleuth:
#    sampler:
#      percentage: 1.0

server:
  port: 2223

eureka:
  client:
    serviceUrl:
      #      defaultZone: http://47.98.189.37:20280/eureka/
      zone2: http://47.98.189.37:20282/eureka/
      zone3: http://47.98.189.37:20283/eureka/
    region: beijing
    availability-zones.beijing: zone3,zone2
    prefer-same-zone-eureka: true
  instance:
    prefer-ip-address: true
    metadata-map.zone: zone3

logging:
  level:
    root: info
    org.springframework.cloud: debug
    com.netflix.discovery: debug


zone.name: zone3