spring:
  application:
    name: service1
#  zipkin:
#    base-url: http://localhost:3337
#  sleuth:
#    sampler:
#      percentage: 1.0

server:
  port: 2222

eureka:
  client:
    serviceUrl:
      zone2: http://localhost:1111/eureka/
    region: skyler-dev
    availability-zones:
      skyler-dev: zone1,zone2
  instance:
    metadata-map.zone: zone2
logging:
  level:
    root: info
    org.springframework.cloud: debug
    com.netflix.discovery: debug
