spring:
  application:
    name: stream-server
  cloud:
    stream:
#      kafka:
#        binder:
#          brokers: localhost:9092
      bindings:
        greetings-in:
          destination: greetings
          contentType: application/json
        greetings-out:
          destination: greetings
          contentType: application/json
server:
  port: 1234

#eureka.client.serviceUrl.defaultZone=http://localhost:1111/eureka/

