server:
  port: 5555

spring:
  application:
    name: zuul-app


#  tomcat:
#    max-threads: 1
#    min-spare-threads: 0

zuul:
  routes:
    api-a-url:
      path: /api-a-url/**
      url: http://localhost:2222/

    api-a:
      path: /api-a/**
      serviceId: service1

    api-b:
      path: /api-b/**
      serviceId: service2
      stripPrefix: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://47.98.189.37:20280/eureka/
  instance:
    prefer-ip-address: true
