server:
  port: 5555

spring:
  application:
    name: zuul-app


#  tomcat:
#    max-threads: 1
#    min-spare-threads: 0

zuul:
  routes:
    api-a-url:
      path: /api-a-url/**
      url: http://localhost:2222/

    api-a:
      path: /api-a/**
      serviceId: service1

    api-b:
      path: /api-b/**
      serviceId: service2
      stripPrefix: true
#  ribbon-isolation-strategy: thread

# hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 3000
## 此属性放在zuul里无效，因为zuul
#hystrix.command.default.execution.isolation.semaphore.maxConcurrentRequests: 5000
hystrix.command.default.execution.isolation.semaphore.maxConcurrentRequests: 5000
#默认20 per 10s--->1000 per 10s
hystrix.command.default.circuitBreaker.requestVolumeThreshold: 10
#默认50%--->80% 10 seconds
hystrix.command.default.circuitBreaker.errorThresholdPercentage: 80

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 8000


eureka:
  client:
    serviceUrl:
      defaultZone: http://47.98.189.37:20280/eureka/
  instance:
    prefer-ip-address: true




logging:
  level:
    root: info
    com.netflix.hystrix: debug
