spring:
  application:
    name: ribbon-consumer
  zipkin:
    base-url: http://localhost:3337
  sleuth:
    sampler:
      percentage: 1.0

server:
  port: 3333

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/