spring.application.name: stream-server

server:
  port: 1234

spring.cloud.stream.kafka.binder.brokers: 127.0.0.1:9092
spring.cloud.stream.kafka.binder.zk-nodes: 127.0.0.1:2181
spring.cloud.stream.kafka.binder.minPartitionCount: 1
spring.cloud.stream.kafka.binder.autoCreateTopics: true
spring.cloud.stream.kafka.binder.autoAddPartitions: true

spring:
  cloud:
    stream:
      binders:
        sourceA:
          destination: test_spring_stream
          group: group-1
          producer:
            partitionCount: 1
      default-binder:

#eureka.client.serviceUrl.defaultZone: http://localhost:1111/eureka/